### ISSUE TITLE
Can not Attach Frida

### ISSUE THREAD

**Issue by sudorphine** [lico-n/ZygiskFrida#39]
I've even finished pausing when I run the app.

However, if I type `frida -U -N com.percent.aos.luckydefense` in cmd, an error occurs.

here is message
```
     ____
    / _  |   Frida 16.3.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Android Emulator 5554 (id=emulator-5554)
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida_tools\reactor.py", line 70, in _run
    work()
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida_tools\application.py", line 601, in _try_start
    self._start()
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida_tools\repl.py", line 220, in _start
    self._set_autoperform(self._autoperform_option)
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida_tools\repl.py", line 614, in _set_autoperform
    if self._is_java_available():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida_tools\repl.py", line 633, in _is_java_available
    script.unload()
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\USERNAME\.conda\envs\py3\Lib\site-packages\frida\core.py", line 310, in unload
    self._impl.unload()
frida.InvalidOperationError: script is destroyed
```

Where did I start with the wrong execution?

Best regard,
user

**Comment by sudorphine** [comment]
oh i fix it
`pip uninstall pygments && pip install pygments`
